//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Decorator
//  @ File Name : Component.java
//  @ Date : 2016/3/11
//  @ Author : blueberry
//
//




public abstract class Component {
	public abstract void operate();
}
