//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Decorator
//  @ File Name : ConcreteCompent.java
//  @ Date : 2016/3/11
//  @ Author : blueberry
//
//




public class ConcreteCompent extends Component {
	
	public void operate() {
		System.out.println("ConcrateComponet.operate()");
	}
	
	public void operate1() {
	}
	
	public void operate2() {
	}
}
