//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Decorator
//  @ File Name : ConcreteDecoratorB.java
//  @ Date : 2016/3/11
//  @ Author : blueberry
//
//




public class ConcreteDecoratorB extends Decorator {
	public ConcreteDecoratorB(Component component) {
		super(component);
	}
	public void operate() {
		super.operate();
		operateB();
	}
	
	public void operateB() {
		System.out.println("ConcreteDecoratorB.operate()");

	}
}
