//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Decorator
//  @ File Name : ConcreteDecoratorA.java
//  @ Date : 2016/3/11
//  @ Author : blueberry
//
//




public class ConcreteDecoratorA extends Decorator  {
	public ConcreteDecoratorA(Component component) {
		super(component);
	}

	
	public void operate() {
		super.operate();
		operateA();
	}
	
	public void operateA() {
		System.out.println("ConcretDecoratorA.operateA()");
	}
}
