//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Component
//  @ File Name : Component.java
//  @ Date : 2016/3/8
//  @ Author : bluberry
//
//




public abstract class Component {
	protected String name;
	public abstract void doSomething();
	public Component(String name) {
		this.name = name;
	}
}
