//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Component
//  @ File Name : Leaf.java
//  @ Date : 2016/3/8
//  @ Author : bluberry
//
//




public class Leaf extends Component {
	Leaf(String name) {
		super(name);
	}

	public void doSomething() {
		System.out.println(name);
	}
	
}
